package:
  name: nbopen
  version: 0.6.0

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - flit
    - py2app # [osx]
    - notebook # [osx]
  run:
    - python
    - notebook <7
    - nbformat
    - requests

about:
  license: BSD-3-Clause
  license_file: LICENSE
